apiVersion: apps/v1
kind: Deployment
metadata:
  name: labreportapp
spec:
  selector:
     matchLabels:
       app: labreportapp
  replicas: 1
  template:
    metadata:
      labels:
        app: labreportapp
    spec:
      cantainers:
        - name: labreportapp
          image: aktansn/labreportapp:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi